# Generated by Django 4.1.3 on 2022-12-10 16:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0013_remove_product_category_remove_product_vendor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('category', models.CharField(choices=[('Poetry', 'Poetry'), ('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Children', 'Children'), ('Education', 'Education'), ('Religion', 'Religion'), ('Self-Help', 'Self-Help'), ('Business', 'Business'), ('Cooking', 'Cooking'), ('Fantasy', 'Fantasy'), ('Young Adult', 'Young Adult'), ('Romance', 'Romance'), ('Mystery', 'Mystery')], max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover', models.ImageField(upload_to='media/images/')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('file', models.FileField(upload_to='media/files/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
        ),
    ]
